# Generated by Django 6.0.5 on 2026-06-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_budgetlimit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcomingpayment',
            name='category',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Spożywcze', 'Spożywcze'), ('Transport', 'Transport'), ('Rozrywka', 'Rozrywka'), ('Rachunki', 'Rachunki'), ('Inne', 'Inne')], default='Inne', max_length=50),
        ),
        migrations.RemoveField(
            model_name='goal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='upcomingpayment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_expense',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='BudgetLimit',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.DeleteModel(
            name='UpcomingPayment',
        ),
    ]
